#!/bin/sh
# Provides: standalone emulation appliance

case "$1" in
	start)
		/usr/bin/emulation-start &
		;;
	stop)
		killall retroarch fbcp-st7789 2>/dev/null || true
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
